jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout project
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      env:
        GRPC_CONSUL_DISCOVERY_PREFER_IP_ADDRESS: true
      name: Build with Gradle
      run: ./gradlew build
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
